item {
  id: 1
  name: 'martabak telor'
}

item {
  id: 2
  name: 'martabak manis'
}

item {
  id: 3
  name: 'ayam goreng'
}

item {
  id: 4
  name: 'kecap'
}

item {
  id: 5
  name: 'ayam pop'
}

item {
  id: 6
  name: 'extra'
}

item {
  id: 7
  name: 'rendang'
}

item {
  id: 8
  name: 'nasi putih'
}

item {
  id: 9
  name: 'bebek bakar'
}

item {
  id: 10
  name: 'bebek goreng'
}

item {
  id: 11
  name: 'iga bakar'
}

item {
  id: 12
  name: 'nasi goreng'
}

item {
  id: 13
  name: 'kerupuk'
}

item {
  id: 14
  name: 'ayam bakar'
}
